name: CI
on:
    pull_request:
    push:
        branches:
            - master
        tags:
            - 'v*.*.*'
    workflow_dispatch:
        inputs:
            ref:
                description: "Commit hash for testing metacall/protocol"
                required: false
                default: "master"
            repo:
                description: "Repository from which we should clone metacall/protocol"
                required: false
                default: "metacall/protocol"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
    contents: read
    id-token: write

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            # Required for local tests
            - name: Setup MetaCall CLI
              run: wget -O - https://raw.githubusercontent.com/metacall/install/master/install.sh | sh

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  registry-url: https://registry.npmjs.org

            - name: Checkout
              uses: actions/checkout@v4

            - name: Installing Dependencies
              run: npm i

            - name: Checkout Protocol Repository
              if: github.event_name == 'workflow_dispatch'
              uses: actions/checkout@v4
              with:
                  repository: ${{ github.event.inputs.repo }}
                  path: /tmp/metacall-protocol
                  ref: ${{ github.event.inputs.ref }}
                  fetch-depth: 0
                  fetch-tags: true

            - name: Pack Latest Protocol
              if: github.event_name == 'workflow_dispatch'
              working-directory: /tmp/metacall-protocol
              run: |
                  npm i
                  npm run build
                  npm pack

            - name: Install Latest Protocol
              if: github.event_name == 'workflow_dispatch'
              run: |
                  npm uninstall @metacall/protocol
                  npm i /tmp/metacall-protocol/metacall-protocol-*.tgz

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Run Tests (production)
              if: github.event_name != 'pull_request'
              run: |
                  echo 'METACALL_AUTH_EMAIL="${{ secrets.METACALL_AUTH_EMAIL }}"' > .env
                  echo 'METACALL_AUTH_PASSWORD="${{ secrets.METACALL_AUTH_PASSWORD }}"' >> .env
                  npm run coverage

            # # TODO: This depends on: https://github.com/metacall/faas/issues/78
            # - name: Run Tests (local)
            #   run: |
            #       cd ..
            #       git clone https://github.com/metacall/faas.git
            #       cd faas
            #       npm install
            #       npm run build
            #       node dist/index.js --version
            #       cd ../deploy
            #       export TEST_DEPLOY_LOCAL="true"
            #       node ../faas/dist/index.js &
            #       sleep 10
            #       mv .env.example .env
            #       npm run coverage

            - name: Publish
              if: startsWith(github.ref, 'refs/tags/')
              run: |
                  unset NODE_AUTH_TOKEN
                  npm publish --provenance
